export const enum ExceptionCodeName {
  EMAIL_CONFLICT = 'EMAIL_CONFLICT',
  INVALID_ENVIRONMENT_VARIABLE = 'INVALID_ENVIRONMENT_VARIABLE',
  INVALID_USER_ROLE_KEY = 'INVALID_USER_ROLE_KEY',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',
  INVALID_JWT = 'INVALID_JWT',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_USER_ID = 'INVALID_USER_ID',
  INVALID_PLANT_ID = 'INVALID_PLANT_ID',
}
